#pragma once
#include <register.h>

THUMB_INSTRUCTION(unimplemented_alu);
THUMB_INSTRUCTION(handle_alu);
THUMB_INSTRUCTION(lsl_imm);
THUMB_INSTRUCTION(lsr_imm);
THUMB_INSTRUCTION(add_reg);
THUMB_INSTRUCTION(add_imm);
THUMB_INSTRUCTION(sbc);
THUMB_INSTRUCTION(mov_imm);
THUMB_INSTRUCTION(mov_high);
THUMB_INSTRUCTION(bic);
THUMB_INSTRUCTION(sub_reg);
THUMB_INSTRUCTION(sub_imm);
THUMB_INSTRUCTION(cmp_imm);